#!/usr/bin/env node
/**
 * Extracts the WABinary token dictionary into src/binary/tokens.generated.ts.
 *
 * This table is data, not logic: it lives in the WhatsApp Web bundle and changes
 * between versions. Writing it by hand is the fastest way to create an invisible
 * bug — a single token out of order shifts every token after it and the server
 * just closes the connection, with no readable error.
 *
 * Accepted sources, tried in order:
 *
 *   1. An installed reference package (baileys, MIT):
 *        npm i -D baileys && npm run vendor:tokens
 *      Once generated, the package can be removed — only the data stays.
 *
 *   2. A WhatsApp Web bundle saved to disk:
 *        node scripts/vendor-tokens.mjs --bundle path/to/bundle.js
 */

import { createRequire } from 'node:module'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const require = createRequire(import.meta.url)
const OUT_PATH = resolve(process.cwd(), 'src/binary/tokens.generated.ts')

const REFERENCE_PATHS = [
	'baileys/lib/WABinary/constants.js',
	'baileys/lib/WABinary/constants',
	'@whiskeysockets/baileys/lib/WABinary/constants.js',
]

function fromReferencePackage() {
	for (const path of REFERENCE_PATHS) {
		try {
			const mod = require(path)
			const single = mod.SINGLE_BYTE_TOKENS
			const double = mod.DOUBLE_BYTE_TOKENS

			if (Array.isArray(single) && Array.isArray(double)) {
				return { single, double, source: path }
			}
		} catch {
			// try the next path
		}
	}

	return null
}

/**
 * In minified bundles both tables appear as array literals of strings. The
 * heuristic: find arrays large enough that contain anchors known to be primary
 * tokens.
 */
function fromBundle(bundlePath) {
	const source = readFileSync(bundlePath, 'utf-8')
	const ANCHORS = ['s.whatsapp.net', 'g.us', 'message']

	const candidates = []
	const arrayRe = /\[(?:\s*(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|null)\s*,?){20,}\]/g

	for (const match of source.matchAll(arrayRe)) {
		try {
			const parsed = JSON.parse(match[0].replace(/'/g, '"'))

			if (Array.isArray(parsed) && ANCHORS.every(a => parsed.includes(a))) {
				candidates.push(parsed)
			}
		} catch {
			// array with escapes JSON.parse rejects — skip it
		}
	}

	if (!candidates.length) {
		return null
	}

	// The primary dictionary is the one holding the anchors; the secondary ones
	// are the next largest arrays. Check the result before trusting it.
	candidates.sort((a, b) => b.length - a.length)

	return { single: candidates[0], double: candidates.slice(1, 5), source: bundlePath }
}

function render({ single, double, source }) {
	const fmt = value => (value === null || value === undefined ? 'null' : JSON.stringify(value))

	const singleLines = single.map(t => `\t${fmt(t)},`).join('\n')
	const doubleLines = double
		.map(sub => `\t[\n${sub.map(t => `\t\t${fmt(t)},`).join('\n')}\n\t],`)
		.join('\n')

	return `// GENERATED BY scripts/vendor-tokens.mjs — DO NOT EDIT BY HAND.
// Source: ${source}
// Generated at: ${new Date().toISOString()}
// Primary tokens: ${single.length} | secondary dictionaries: ${double.length}

import type { TokenDictionary } from './tokens.ts'

const single: readonly (string | null)[] = [
${singleLines}
]

const double: readonly (readonly string[])[] = [
${doubleLines}
]

export const VENDORED_TOKENS: TokenDictionary = { single, double }
`
}

function main() {
	const bundleIdx = process.argv.indexOf('--bundle')
	const result = bundleIdx > -1 ? fromBundle(process.argv[bundleIdx + 1]) : fromReferencePackage()

	if (!result) {
		console.error(
			[
				'Could not extract the token dictionary.',
				'',
				'Option 1 — reference package (MIT):',
				'  npm i -D baileys && npm run vendor:tokens',
				'',
				'Option 2 — a WhatsApp Web bundle saved to disk:',
				'  node scripts/vendor-tokens.mjs --bundle ./bundle.js',
			].join('\n'),
		)
		process.exit(1)
	}

	writeFileSync(OUT_PATH, render(result), 'utf-8')

	console.log(`Dictionary written to ${OUT_PATH}`)
	console.log(`  source: ${result.source}`)
	console.log(`  primary tokens: ${result.single.length}`)
	console.log(`  secondary dictionaries: ${result.double.length} (${result.double.map(d => d.length).join(', ')} tokens)`)
	console.log('')
	console.log('Run `npm test` — the sanity test checks the table is coherent.')
}

main()
